---
- name: Create /etc/containerd directory
  file:
    path: /etc/containerd
    state: directory
  notify: Restart containerd

- name: Check if containerd config file exists
  stat:
    path: /etc/containerd/config.toml
  register: containerd_config_file

- name: Generate default containerd config
  command: /usr/local/bin/containerd config default
  register: containerd_config
  when: not containerd_config_file.stat.exists
  changed_when: true
  notify: Restart containerd

- name: Write containerd config to file
  copy:
    content: "{{ containerd_config.stdout }}"
    dest: /etc/containerd/config.toml
  when: containerd_config.stdout is defined and not containerd_config_file.stat.exists
  notify: Restart containerd

- name: Ensure SystemdCgroup is set
  replace:
    path: /etc/containerd/config.toml
    regexp: '^(\s*SystemdCgroup\s*=\s*)false'
    replace: '\1true'
  notify: Restart containerd

- name: Ensure sandbox_image is set
  replace:
    path: /etc/containerd/config.toml
    regexp: '^(\s*sandbox_image\s*=\s*).*'
    replace: '\1"registry.k8s.io/pause:3.9"'
  notify: Restart containerd
