---
- name: Include CNI configuration for Flannel
  import_tasks: flannel.yml
  when: cni_network == "flannel"

- name: Include CNI configuration for Calico
  import_tasks: calico.yml
  when: cni_network == "calico"
