---
galaxy_info:
  role_name: kubeadm
  namespace: default
  author: Jonata Martins
  description: Config a K8s cluster with kubeadm
  license: MIT
  min_ansible_version: "2.9"
  galaxy_tags:
    - kubernetes
    - k8s
    - kubeadm